version: "3.9"
services:
  lgsfrontend:
    image: quay.io/kurama/lgs-frontend:latest
    restart: always
    labels:
      - traefik.frontend.rule=Host:labyrinthglobalsolutions.com,www.labyrinthglobalsolutions.com
    networks:
     - web
    ports:
      - "3008:3008"
networks:
 web:
   external: true