version: "3.9"
services:
  lgsfrontend:
    build: .
    restart: always
    # labels:
    #   - traefik.frontend.rule=Host:
    networks:
     - web
    ports:
      - "3008:3008"
networks:
 web:
   external: true